version: "3.4"
services:
  sample-api:
    container_name: sample-api
    image: mcr.microsoft.com/dotnet/sdk:5.0
    volumes:
      - .:/api
    working_dir: /api
    command: "dotnet run"
    ports:
      - "5002:5283"